---
- name: Patching Kernel
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: confirm kernel version
      shell: "uname -a"


    - name: Create  SSH key for user jsmith in ~name/.ssh/id_rsa
      user:
        name: name 
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa

